services:
  db:
    image: postgres:16-alpine
    container_name: systemphp_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: systemphp
      POSTGRES_USER: systemphp_app
      POSTGRES_PASSWORD: trocaesta
    ports:
      - "127.0.0.1:5435:5432"
    volumes:
      - systemphp_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U systemphp_app"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  systemphp_db_data:
